### ISSUE TITLE
Hailo requires Test::Script and MooseX::Getopt::Dashes

### ISSUE THREAD

**Issue by mxey** [hinrik/hailo#14]
Hailo requires Test::Script and MooseX::Getopt::Dashes for build/running, but META.yml does not mention them.

**Comment by hinrik** [comment]
I just fixed this. Thanks.

**Comment by avar** [comment]
We needed to declare Test::Script, but MooseX::Getopt::Dashes is part of MooseX::Getopt which I had already declared:

```
c58d7bd0 (Ævar Arnfjörð Bjarmason 2010-01-30 13:56:46 +0000 27) requires       ('Moose'                         => '0');
c58d7bd0 (Ævar Arnfjörð Bjarmason 2010-01-30 13:56:46 +0000 28) requires       ('MooseX::Getopt'                => '0');
e6412444 (Hinrik Örn Sigurðsson   2010-02-07 02:23:45 +0000 29) requires       ('MooseX::Getopt::Dashes'        => '0');
```

Did this actually give an error?

**Comment by hinrik** [comment]
No, I think I just added this out of the habit of declaring explicit dependencies on the modules we use directly, rather than depending on some module from the distribution and assuming we get the other modules currently bundled with it. Though not common, this guards against the case when the distribution author moves a certain module to its own distribution.

**Comment by avar** [comment]
The question was meant for mxey. Declaring dependencies explicitly is a good idea, but I was wondering if he ran into some build problem because MX::GO::D wasn't declared, that would be odd.

**Comment by mxey** [comment]
The problem is that MooseX::Getopt is used during the test, but not declared as required for testing.
